### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by koola**
I would like to suggest the following changes. I'd still prefer to use getLocation for FF/IE although if there's any benefit with the offset that you suggested, I'd like to hear it. Thanks!

### CODE REVIEW

**Comment by wswebcreation** [comment]
Hi @koola ,

Tnx for the review and suggestions. I'll merge them and add a PR. Is there also a way we can get in contact so I can help you more with contribution?

**Comment by koola** [comment]
Hey @wswebcreation, sure! I'm on Skype under james.tw.cn

**Comment by wswebcreation** [comment]
Do you also have Hangouts? I don't have / use Skype :)

**Comment by koola** [comment]
Yeah, jrmerson@thoughtworks.com

**Pull request merged**
